# Generated by Django 6.0.6 on 2026-06-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('device_type', models.CharField(choices=[('gate', 'Gate'), ('camera', 'Camera'), ('motion_sensor', 'Motion Sensor'), ('thermostat', 'Thermostat'), ('lock', 'Smart Lock'), ('light', 'Light'), ('hub', 'Hub')], max_length=32)),
                ('category', models.CharField(choices=[('Security', 'Security'), ('Climate', 'Climate'), ('Lighting', 'Lighting')], max_length=32)),
                ('status_text', models.CharField(blank=True, max_length=160)),
                ('float_value', models.FloatField(default=0.0)),
                ('icon_name', models.CharField(max_length=32)),
                ('is_on', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('mqtt_topic', models.CharField(blank=True, max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='savehaven_app.home')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('home', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('Critical', 'Critical'), ('Warning', 'Warning'), ('Info', 'Info')], default='Info', max_length=16)),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='savehaven_app.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='savehaven_app.home')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_armed', models.BooleanField(default=False)),
                ('armed_mode', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Night', 'Night'), ('Disarmed', 'Disarmed')], default='Disarmed', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_state', to='savehaven_app.home')),
            ],
        ),
    ]
